on:
  push:
    branches: ['*']

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Prepare Ubuntu
        run: |
          chmod +x ./dep-ubuntu.sh && ./dep-ubuntu.sh

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          channel: 'stable'

      - name: Flutter Version
        run: flutter --version

      - name: Build
        run: |
          flutter pub get && flutter clean && flutter build linux

      - name: Tests
        run: flutter test
